name: casabosco
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Casa Bosco
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#aeaeae'
    - '#d9d9d9'
    - '#505050'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
